### ISSUE TITLE
provide description for STRAWBERRY app (and maybe open it's issue tracker)

### ISSUE THREAD

**Issue by kolAflash** [Eve-146T/EVILSPIN#2]
I'm writing this, because it looks like you @Eve-146T added the STRAWBERRY app and also the Evil.Spin app to F-Droid.  
https://gitlab.com/fdroid/fdroiddata/-/blob/2bf15ed5a41b4cf811bcb79f2482340c7e165a6f/metadata/straw.berry.yml  
https://gitlab.com/fdroid/fdroiddata/-/blob/e6357392256fd880808e6f2846dc335c9c44d152/metadata/evil.spin.yml  
_(same username on [GitHub](https://github.com/Eve-146T) and [GitLab](https://gitlab.com/Eve-146T))_

If you added the apps to F-Droid, please add a proper description to the Strawberry app.  
Also a polite app listed on F-Droid should have proper description in it's commits. Please don't just put 🍓 in there.

Also you might have a look at this F-Droid issue.  
https://gitlab.com/fdroid/fdroiddata/-/issues/3377  
It would be helpful if you clarify what especially the Strawberry app is for. If it has no clear use or is just for testing, please state why you added it to the F-Droid repo.

&nbsp;

You might also open the issue tracker for the [STRAWBERRY repo](https://github.com/Eve-146T/STRAWBERRY). I guess a decent app in the public F-Droid repo should have an existing issue tracker.

**Comment by Eve-146T** [comment]
🍓
