### ISSUE TITLE
Font is too big when there's a lot of options

### ISSUE THREAD

**Issue by quicksc0p3r** [Eve-146T/EVILSPIN#3]
If you add a lot of options to the wheel, the text will be slightly cut off due to being too big. Add font scaling based on the number of options
![Screenshot_2024-08-01-10-50-58-563_evil spin-edit](https://github.com/user-attachments/assets/06e29ab1-88f2-4f89-9035-7b7252770fa1)

**Comment by Eve-146T** [comment]
I've added font scaling, here is how it looks now:
![image](https://github.com/user-attachments/assets/43e3e19f-2d6f-4e6b-b9b6-e513c0bb727f)


there is a new issue where the new text is now waay to small, but ill deal with that later: (see bottom left, the yellow slice)
![image](https://github.com/user-attachments/assets/22832405-17b2-4433-bdbd-a4d7098ae7cd)
